Canton a analizar: Milagro

Provincia: Guayas

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#conda activate p2-statistics

![dic](dic.png)


In [44]:
micro_1 = pd.read_csv('SBAC19_micro_514852_20200325_CSV.csv', sep=';')
micro_1.drop('codigo', axis=1, inplace=True)

variables = ['financiamiento', 'tp_sexo', 'tp_area', 'isec', 'inev', 'pes', 'imat',
       'ilyl', 'icn', 'ies', 'nl_imat', 'nl_ilyl', 'nl_icn', 'nl_ies',
       'nl_inev']

for variable in variables:
    print(f"Unique values of {variable}:")
    print(micro_1[variable].unique())
    print()


C:\Users\HOME\AppData\Local\Temp\ipykernel_3172\3232250395.py:1: DtypeWarning: Columns (2,22,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  micro_1 = pd.read_csv('SBAC19_micro_514852_20200325_CSV.csv', sep=';')


Unique values of financiamiento:
[     1      2      3 999999]

Unique values of tp_sexo:
[1 2]

Unique values of tp_area:
[ 1  2 98]

Unique values of isec:
[',86847' '-1,14563' ',21734' ... '-,17423' '-,196352309' '-,651073539']

Unique values of inev:
['7,55' '7,5' '5,93' '8,04' '7,86' '8,36' '8,56' '8,44' '8,47' '8,76'
 '8,65' '7,8' '8,82' '9,02' '8,94' '8,18' '8,24' '8,79' '9,17' '9,22'
 '9,08' '8,85' '7,63' '8,88' '8,7' '8,91' '8,99' '9,28' '8,13' '7,75'
 '8,01' '7,53' '7,31' '7,58' '6,79' '7,64' '7,43' '8,07' '7,89' '7,05'
 '7,7' '8,21' '7,92' '9,11' '8,27' '7,81' '7,29' '8,09' '6,41' '7,32'
 '6,73' '7,2' '7,21' '7,78' '7,49' '7,36' '7,35' '6,74' '6,61' '7,52'
 '6,89' '7,48' '7,72' '6,95' '7,15' '7,46' '6,72' '7' '7,44' '6,57' '8,67'
 '8,15' '7,13' '7,69' '7,24' '8,38' '7,18' '6,99' '7,1' '6,71' '7,65'
 '7,66' '6,91' '6,53' '7,03' '6,97' '7,02' '6,98' '7,38' '6,75' '5,59'
 '7,04' '6,9' '6,55' '6,94' '7,27' '999999' '7,84' '7,98' '7,4' '7,28'
 '7,41' '6,36' '6,25' '8,53' '5,27' '

In [45]:
micro_2 = pd.read_csv('SBAC20_micro_272370_20210121_CSV.csv', sep=';')
micro_2.drop('codigo', axis=1, inplace=True)

variables = ['financiamiento', 'tp_sexo', 'tp_area', 'isec', 'inev', 'pes', 'imat',
       'ilyl', 'icn', 'ies', 'nl_imat', 'nl_ilyl', 'nl_icn', 'nl_ies',
       'nl_inev']

for variable in variables:
    print(f"Unique values of {variable}:")
    print(micro_2[variable].unique())
    print()

C:\Users\HOME\AppData\Local\Temp\ipykernel_3172\1851611013.py:1: DtypeWarning: Columns (2,22,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  micro_2 = pd.read_csv('SBAC20_micro_272370_20210121_CSV.csv', sep=';')


Unique values of financiamiento:
[     1      3      2 999999]

Unique values of tp_sexo:
[1 2]

Unique values of tp_area:
[ 2  1 98]

Unique values of isec:
['-,29756' '1,98499' '-1,12751' ... ',73235' '-1,34887' ',2267']

Unique values of inev:
['7,3' '7,22' '7,38' '7,27' '6,69' '7,66' '7,21' '6,92' '7,25' '7,75' '7'
 '6,83' '7,12' '8,32' '6,87' '6,72' '7,19' '6,75' '6,68' '7,06' '7,14'
 '7,15' '7,33' '7,45' '7,36' '7,46' '6,58' '7,02' '7,17' '7,54' '8,74'
 '6,8' '7,05' '999999' '6,33' '7,63' '6,16' '7,64' '7,41' '6,77' '8,85'
 '6,36' '6,88' '6,55' '7,31' '6,85' '7,28' '7,09' '7,08' '6,73' '6,76'
 '7,4' '7,04' '7,59' '7,18' '7,78' '6,53' '7,44' '6,98' '7,74' '6,62'
 '6,56' '7,24' '6,66' '6,37' '6,5' '7,56' '7,77' '6,74' '6,46' '7,61'
 '7,29' '7,93' '6,95' '6,93' '6,78' '7,34' '6,81' '6,99' '7,62' '7,39'
 '7,55' '6,64' '8,08' '7,96' '6,44' '7,49' '7,23' '6,1' '7,47' '7,73'
 '7,26' '7,48' '7,7' '6,57' '6,86' '6,49' '6,71' '7,2' '7,07' '8,05'
 '7,01' '6,94' '7,16' '6,31' '6,08' '6,63' '

In [32]:
micro_milagro = micro[micro["id_cant"] == 901]

columns_to_drop = ['ciclo', 'amie', 'nm_regi', 'es_regeva', 'id_zona', 'id_dist', 'id_circ', 'id_prov', 'id_cant', 'id_parr']
micro_milagro.drop(columns_to_drop, axis=1, inplace=True)

to_drop = ["tp_sost", "na_eano", "etnibbe", 'discapacidad', 'quintil', 'poblacion', 'estado', "deshonestidad"]
micro_milagro.drop(to_drop, axis=1, inplace=True)
micro_milagro

C:\Users\HOME\AppData\Local\Temp\ipykernel_3172\4249648222.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  micro_milagro.drop(columns_to_drop, axis=1, inplace=True)
C:\Users\HOME\AppData\Local\Temp\ipykernel_3172\4249648222.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  micro_milagro.drop(to_drop, axis=1, inplace=True)


financiamiento  tp_sexo  tp_area      isec    inev     pes    imat  \
23160                1        1        2    ,77707    6,39     565    6,63   
23161                1        1        2   -,80712    7,64     685    7,56   
23162                1        1        2    ,92683    6,91     600       7   
23163                1        2        2  -1,73878    7,06     635    7,19   
23164                1        1        2  -1,03549    8,18     755     8,5   
...                ...      ...      ...       ...     ...     ...     ...   
272128          999999        1        2    ,92683  999999     565  999999   
272193          999999        1        2    1,2552  999999     570  999999   
272256          999999        2        2  -1,52631  999999     645  999999   
272261          999999        2        2       ,05  999999     615  999999   
272344          999999        1        2    999999  999999  999999  999999   

          ilyl     icn     ies  nl_imat  nl_ilyl  nl_icn  nl_ies  nl_inev  
23160     6,33    7,11     5,5   999999   999999  999999  999999   999999  
23161     7,35    7,44     8,2   999999   999999  999999  999999   999999  
23162     6,33       7     7,3   999999   999999  999999  999999   999999  
23163        6    7,89    7,15   999999   999999  999999  999999   999999  
23164     8,06    8,11    8,05   999999   999999  999999  999999   999999  
...        ...     ...     ...      ...      ...     ...     ...      ...  
272128  999999  999999  999999   999999   999999  999999  999999   999999  
272193  999999  999999  999999   999999   999999  999999  999999   999999  
272256  999999  999999  999999   999999   999999  999999  999999   999999  
272261  999999  999999  999999   999999   999999  999999  999999   999999  
272344  999999  999999  999999   999999   999999  999999  999999   999999  

[64698 rows x 15 columns]

In [33]:
micro_milagro.columns

Index(['financiamiento', 'tp_sexo', 'tp_area', 'isec', 'inev', 'pes', 'imat',
       'ilyl', 'icn', 'ies', 'nl_imat', 'nl_ilyl', 'nl_icn', 'nl_ies',
       'nl_inev'],
      dtype='object')

In [34]:
micro_milagro.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64698 entries, 23160 to 272344
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   financiamiento  64698 non-null  int64 
 1   tp_sexo         64698 non-null  int64 
 2   tp_area         64698 non-null  int64 
 3   isec            64698 non-null  object
 4   inev            64698 non-null  object
 5   pes             64698 non-null  int64 
 6   imat            64698 non-null  object
 7   ilyl            64698 non-null  object
 8   icn             64698 non-null  object
 9   ies             64698 non-null  object
 10  nl_imat         64698 non-null  int64 
 11  nl_ilyl         64698 non-null  int64 
 12  nl_icn          64698 non-null  int64 
 13  nl_ies          64698 non-null  int64 
 14  nl_inev         64698 non-null  int64 
dtypes: int64(9), object(6)
memory usage: 7.9+ MB


In [35]:
variables = ['financiamiento', 'tp_sexo', 'tp_area', 'isec', 'inev', 'pes', 'imat',
       'ilyl', 'icn', 'ies', 'nl_imat', 'nl_ilyl', 'nl_icn', 'nl_ies',
       'nl_inev']

for variable in variables:
    print(f"Unique values of {variable}:")
    print(micro_milagro[variable].unique())
    print()




Unique values of financiamiento:
[     1      2      3 999999]

Unique values of tp_sexo:
[1 2]

Unique values of tp_area:
[2 1]

Unique values of isec:
[',77707' '-,80712' ',92683' ... ',3364' '1,19369' ',31248']

Unique values of inev:
['6,39' '7,64' '6,91' '7,06' '8,18' '6,75' '7,56' '7,62' '6,18' '7,23'
 '7,27' '6,71' '7,5' '6,87' '8,23' '8,22' '7,12' '7,17' '6,85' '7,31'
 '7,41' '7,74' '7,2' '7,24' '6,84' '6,77' '7,38' '6,76' '7,43' '7,91'
 '8,58' '7,32' '7,33' '7,73' '8,78' '6,94' '9,31' '7,1' '6,6' '7,65'
 '7,11' '7,7' '7,59' '7,79' '8,06' '7,86' '7,51' '7,69' '7,81' '8,05'
 '7,29' '7,76' '6,82' '6,48' '8,11' '7,09' '8,57' '8,03' '8,14' '7,71'
 '9,08' '7,14' '9,28' '6,66' '7' '6,96' '7,37' '6,69' '6,37' '9,3' '7,44'
 '7,15' '7,49' '7,52' '7,35' '7,53' '9,27' '8,97' '7,25' '7,61' '6,78'
 '7,45' '6,98' '6,68' '7,47' '7,21' '6,7' '6,57' '7,4' '8,29' '7,92'
 '6,89' '7,05' '6,83' '7,46' '6,02' '6,97' '9,37' '7,04' '7,48' '7,34'
 '6,72' '8,61' '8,4' '6,24' '6,81' '7,75' '7,55' '6,95' 

In [36]:
micro_milagro.describe()

financiamiento       tp_sexo       tp_area            pes   nl_imat  \
count    64698.000000  64698.000000  64698.000000   64698.000000   64698.0   
mean    296238.611735      1.481483      1.973291   54067.168970  999999.0   
std     456599.627896      0.499661      0.161232  224745.901967       0.0   
min          1.000000      1.000000      1.000000       0.000000  999999.0   
25%          1.000000      1.000000      2.000000     610.000000  999999.0   
50%          2.000000      1.000000      2.000000     650.000000  999999.0   
75%     999999.000000      2.000000      2.000000     720.000000  999999.0   
max     999999.000000      2.000000      2.000000  999999.000000  999999.0   

        nl_ilyl    nl_icn    nl_ies   nl_inev  
count   64698.0   64698.0   64698.0   64698.0  
mean   999999.0  999999.0  999999.0  999999.0  
std         0.0       0.0       0.0       0.0  
min    999999.0  999999.0  999999.0  999999.0  
25%    999999.0  999999.0  999999.0  999999.0  
50%    999999.0  999999.0  999999.0  999999.0  
75%    999999.0  999999.0  999999.0  999999.0  
max    999999.0  999999.0  999999.0  999999.0

In [37]:
micro_milagro.columns

Index(['financiamiento', 'tp_sexo', 'tp_area', 'isec', 'inev', 'pes', 'imat',
       'ilyl', 'icn', 'ies', 'nl_imat', 'nl_ilyl', 'nl_icn', 'nl_ies',
       'nl_inev'],
      dtype='object')